---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: foo
  namespace: delivery
spec:
  serviceAccountName: delivery-sa
  packageRef:
    refName: foo.vmware.com
    versionSelection:
      constraints: ">0.0.0"